spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_db
    username: store_admin_user
    password: G@mi5DWor1D
    driveClassName: com.mysql.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          globally_quoted_identifiers: true
