spring:
  datasource:
    url: jdbc:mysql://localhost:3306/store_db
    username: store_admin_user
    password: G@mi5DWor1D
    driverClassName: com.mysql.jdbc.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
    timeBetweenEvictionRunsMillis: 3600000

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          globally_quoted_identifiers: true
